# Syntax reference https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Environment reference https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
name: CI-cygwin

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
    tags:
      - '2.*'
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: cmd

jobs:
  build_cygwin:
    strategy:
      matrix:
        os: [windows-2022]
        arch: [x64]
        include:
          - platform: 'x86_64'
            # python3 is necessary so we can execute addons
            packages: |
              gcc-g++
              python3
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          platform: ${{ matrix.arch }}
          packages: ${{ matrix.packages }}

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          check-latest: true

      - name: Install missing Python packages
        run: |
          python -m pip install pip --upgrade || exit /b !errorlevel!
          python -m pip install pytest || exit /b !errorlevel!
          python -m pip install pytest-custom_exit_code || exit /b !errorlevel!
          python -m pip install pytest-timeout || exit /b !errorlevel!

      # Cygwin will always link the binaries even if they already exist. The linking is also extremely slow. So just run the "check" target which includes all the binaries.
      - name: Build all and run test
        run: |
          C:\cygwin\bin\bash.exe -l -c cd %GITHUB_WORKSPACE% && make VERBOSE=1 -j2 check

      - name: Extra test for misra
        run: |
          cd %GITHUB_WORKSPACE%\addons\test || exit /b !errorlevel!
          ..\..\cppcheck.exe --dump -DDUMMY --suppress=uninitvar --inline-suppr misra\misra-test.c --std=c89 --platform=unix64 || exit /b !errorlevel!
          python3 ..\misra.py -verify misra\misra-test.c.dump || exit /b !errorlevel!
          ..\..\cppcheck.exe --addon=misra --enable=style --inline-suppr --enable=information --error-exitcode=1 misra\misra-ctu-1-test.c misra\misra-ctu-2-test.c || exit /b !errorlevel!

      - name: Run test/cli
        run: |
          cd test/cli || exit /b !errorlevel!
          python3 -m pytest -Werror --strict-markers -vv || exit /b !errorlevel!
