# Syntax reference https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Environment reference https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
name: CI-windows

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - '2.*'
    tags:
      - '2.*'
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: cmd

jobs:

  # TODO: use Debug build to speed it up?
  build_qt:
    strategy:
      matrix:
        os: [windows-2025]
        qt_ver: [6.10.0]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Visual Studio environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Qt ${{ matrix.qt_ver }}
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          modules: 'qtcharts'
          setup-python: 'false'
          cache: true

      - name: Run CMake
        run: |
          rem TODO: enable rules?
          rem specify Release build so matchcompiler is used
          cmake -S . -B build -Werror=dev --warn-uninitialized -DCMAKE_BUILD_TYPE=Release -DCMAKE_COMPILE_WARNING_AS_ERROR=On -DBUILD_TESTING=Off -DBUILD_GUI=On -DWITH_QCHART=On -DBUILD_TRIAGE=On -DBUILD_ONLINE_HELP=On -DCMAKE_INSTALL_PREFIX=cppcheck-cmake-install -DCMAKE_COMPILE_WARNING_AS_ERROR=On || exit /b !errorlevel!

      - name: Build GUI release
        run: |
          cmake --build build --target cppcheck-gui --config Release || exit /b !errorlevel!

      - name: Deploy GUI
        run: |
          windeployqt build\bin\Release || exit /b !errorlevel!
          del build\bin\Release\cppcheck-gui.ilk || exit /b !errorlevel!
          del build\bin\Release\cppcheck-gui.pdb || exit /b !errorlevel!

      # TODO: run GUI tests

      - name: Run CMake install
        run: |
          rem TODO: this performs a Debug build
          rem TODO: the Qt DLLS are not being installed (because of the missing windeployqt?)
          cmake --build build --target install
          rem TODO: validate the installed files
