# Syntax reference https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Environment reference https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
name: scriptcheck

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - '2.*'
    tags:
      - '2.*'
  pull_request:

permissions:
  contents: read

jobs:

  dmake:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-15, windows-2025]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: run dmake
        run: |
          make -j3 CXXOPTS="-Werror" run-dmake

      - name: check diff
        run: |
          git diff --exit-code
